# Generated by Django 4.2 on 2023-09-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodname',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='foodname',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Rate'),
        ),
    ]
