# Generated by Django 4.2 on 2023-09-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_foodname_description_alter_foodname_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodname',
            name='type_food',
            field=models.CharField(choices=[('drinks', 'Drinks'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='drinks', max_length=10, verbose_name='Type Of Food'),
        ),
    ]
