# Generated by Django 4.2 on 2023-10-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_foodname_type_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Image Title')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Image')),
            ],
        ),
    ]
