# Generated by Django 4.2 on 2023-10-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_imageslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
            ],
        ),
    ]
