# Generated by Django 4.2 on 2023-10-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('x_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='X Username')),
                ('facebook_username', models.CharField(blank=True, max_length=254, null=True, verbose_name='FB Username')),
                ('image', models.ImageField(upload_to='stuff/', verbose_name='Stuf Image')),
            ],
        ),
    ]
