# Generated by Django 4.2 on 2023-10-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_rename_stuff_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('persons', models.IntegerField(verbose_name='Persons')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(upload_to='stuff/', verbose_name='Staff Image'),
        ),
    ]
