# Generated by Django 4.2 on 2023-10-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contact_alter_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='persons',
            field=models.IntegerField(default=0, verbose_name='Persons'),
        ),
    ]
