# Generated by Django 4.2 on 2023-09-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='FullName')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phonenumber')),
                ('numbers', models.IntegerField(verbose_name='Person')),
                ('date', models.DateField(verbose_name='Choose a day')),
                ('time', models.DateTimeField(verbose_name='Choose a Time')),
            ],
        ),
    ]
