# Generated by Django 4.2 on 2023-09-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(verbose_name='Choose a Time'),
        ),
    ]
